### ISSUE TITLE
Sugestão: Link da nota fiscal na área do cliente

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#1]
Olá, bom dia, estou utilizando o modulo e gostaria de saber se é possível ter um link da nota fiscal na fatura do cliente:

![Captura de tela de 2020-07-16 12-00-33](https://user-images.githubusercontent.com/636225/87687401-1024fe80-c75c-11ea-9cd0-dbd13d5738a8.png)

Obrigado

**Comment by mauriciogofas** [comment]
Sim, vamos adicionar essa funcionalidade em breve. Também estamos desenvolvendo formas de exibir as NFEs na área do cliente e incluir nos emails, de nova fatura e(ou) de confirmação de pagamento.

**Comment by souzadavi** [comment]
Para inserir um link da nota fiscal direto na fatura do template do WHMCS, utilize o exemplo abaixo:

`<a` href="/modules/addons/gofasnfeio/pdf.php?invoice_id={$invoiceid}" target="_blank" class="btn btn-link"><i class="fal fa-file-invoice" aria-hidden="true"></i> NOTA FISCAL</a>`
