### ISSUE TITLE
Gerar PDF, várias janelas

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#101]
Ao solicitar para gerar o PDF ele abre várias janelas. Ele não abre apenas as notas emitidas daquela fatura.

/modules/addons/gofasnfeio/createpdf.php?nfe_id=1293

**Comment by andrekutianski** [comment]
Isto ocorre na visão do administrador ou do usuário? Qual sua versão do módulo e WHMCS?

**Comment by souzadavi** [comment]
isso ocorre na versão do usuário dentro da fatura. São as últimas versões.

**Comment by andrekutianski** [comment]
irei vincular esta questão a #69
