### ISSUE TITLE
Agendamento de emissão de nota fiscal não funciona

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#103]
Olá pessoal, ao utilizar a opção de agendamento de emissão de nota fiscal, o sistema para de emitir nota fiscal manualmente e automaticamente.

![Screenshot from 2021-11-30 16-56-16](https://user-images.githubusercontent.com/636225/144244722-b538000f-bfb3-44d2-a9cb-b5e0844bc6df.png)

**Comment by andrekutianski** [comment]
@souzadavi poderia confirmar para mim:

* versão do WHMCS
* versão do módulo
* versão do PHP

Tentarei reproduzir o mesmo cenário que o seu para realizar alguns testes.

**Comment by souzadavi** [comment]
@andrekutianski obrigado pelo retorno segue informações: WHMCS Versão: 8.3.1 PHP Version 7.4.25 Modulo versão: 1.4.5

**Comment by andrekutianski** [comment]
@souzadavi tive um problema com meu ambiente de desenvolvimento e somente consegui normalizar tudo agora. Vou inciar os testes com as versões que você informou.

**Comment by andrekutianski** [comment]
Testei na referida versão e pelo que pude notar a tarefa diária das notas não está sendo executada. Também tentei com as versões anteriores e a cron também não rodou.

@souzadavi para você parou após a atualização para a 1.4.5?

**Comment by souzadavi** [comment]
@andrekutianski tentei começar a usar este recurso agora.

**Comment by andrekutianski** [comment]
Já enviarei um fix.

**Comment by andrekutianski** [comment]
@souzadavi coloquei uma versão em pre-release com a correção desta questão. A versão está disponível em https://github.com/nfe/whmcs-addon/releases/tag/v1.4.6

O comportamento esperado agora é:

- Quando a opção "Agendar Emissão" estiver configurado, as notas serão emitidas no número de dias informado após o pagamento. 

> Por exemplo, o dia configurado em "Agendar Emissão" é 3, ou seja, emitir NF 3 dias após o pagamento da fatura; o dia atual é 20, então todas as notas que tiveram seu pagamento confirmado (marcadas como paga) seja manualmente ou através de uma transação no dia 17 terão suas notas geradas na execução da cron diária do WHMCS (Daily Cron Run).

- As notas serão inseridas na fila e processadas para emissão através da rotina de invocação da cron, conforme o tempo configurado no seu crontab.

> Após as NFs estarem na fila, outra rotina irá emitir as mesmas. Esta rotina também irá verificar qualquer nota que esteja na fila (seja qual for o acionador de sua geração) e irá acionar sua emissão.

Recomendo realizar um backup completo do seu banco de dados assim como do WHMCS antes de realizar qualquer atualização.
