### ISSUE TITLE
[BUG] Não emite varias notas ao gerar varias faturas

### ISSUE THREAD

**Issue by ibinetwork** [nfe/whmcs-addon#108]
**Descreva o erro**

Ao gerar faturas mensais não gera a nota fiscal, gera apenas uma e as restantes não gera.

**Como reproduzir**

**Comportamento esperado**
Esperava que fosse gerado todas as notas fiscais de acordo com as faturas de todos clientes.

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

**Ambiente e versões:**
 - Versão do módulo: 1.4.6
 - Versão do WHMCS: 8.2.1
 - Versão do PHP: 7.4

**Comment by andrekutianski** [comment]
@ibinetwork os produtos/serviços da fatura possuem códigos de serviço personalizados ou utilizam todos o padrão?

**Comment by ibinetwork** [comment]
Todos padrão.

**Comment by andrekutianski** [comment]
@ibinetwork em meus testes quando é emitida uma fatura com diferentes produtos, mas com mesmo código de serviço (o padrão) está sendo emitida apenas uma NF para todos os produtos/serviços.

Agora quando gero um pedido ou fatura de produtos com diferentes códigos de serviços, são geradas diferentes NF's (imagem a seguir)

![image](https://user-images.githubusercontent.com/5316107/153919066-7e58128f-0b27-48da-917d-960765cba8a1.png)

Estou verificando o que está ocasionando esta divergência no comportamento, já que antes da versão 1.4.6 era emitida uma NF para cada produto/serviço independente do código ser o mesmo ou não.

**Comment by ibinetwork** [comment]
@andrekutianski acho que me expressei mal. Ao gerar varias faturas de clientes diferentes com o mesmo vencimento que acontece o problema no meu caso. Por exemplo no dia 1 do mês meu sistema gera em torno de 40 faturas de clientes diferentes com vencimento no dia 10, e apenas a primeira fatura gerada emite a nota fiscal, a restante eu preciso entrar uma a uma e clicar em emitir nfe, imagina o trabalho rsrsrs.

**Comment by andrekutianski** [comment]
> @andrekutianski acho que me expressei mal. Ao gerar varias faturas de clientes diferentes com o mesmo vencimento que acontece o problema no meu caso. Por exemplo no dia 1 do mês meu sistema gera em torno de 40 faturas de clientes diferentes com vencimento no dia 10, e apenas a primeira fatura gerada emite a nota fiscal, a restante eu preciso entrar uma a uma e clicar em emitir nfe, imagina o trabalho rsrsrs.

Entendi! Você está usando a configuração de emitir NF na geração da fatura?

**Comment by ibinetwork** [comment]
> > @andrekutianski acho que me expressei mal. Ao gerar varias faturas de clientes diferentes com o mesmo vencimento que acontece o problema no meu caso. Por exemplo no dia 1 do mês meu sistema gera em torno de 40 faturas de clientes diferentes com vencimento no dia 10, e apenas a primeira fatura gerada emite a nota fiscal, a restante eu preciso entrar uma a uma e clicar em emitir nfe, imagina o trabalho rsrsrs.
> 
> Entendi! Você está usando a configuração de emitir NF na geração da fatura?

Sim, emitir NF na geração da fatura

**Comment by ibinetwork** [comment]
> @ibinetwork uma dúvida, você atualizou a partir de 1.4.5 para a 1.4.6 ou utilizava uma versão anterior?

Atualizei do 1.4.4 para o 1.4.6, não tem opção para baixar a versão 1.4.5

**Comment by andrekutianski** [comment]
> > @ibinetwork uma dúvida, você atualizou a partir de 1.4.5 para a 1.4.6 ou utilizava uma versão anterior?
> 
> Atualizei do 1.4.4 para o 1.4.6, quando atualizei não tinha achado a opção para baixar a versão 1.4.5

obrigado, realizarei um teste similar ao seu procedimento e logo informo os resultados. Fiz uma bateria de laboratórios e cenários para teste e também compartilharei os resultados.

**Comment by ibinetwork** [comment]
Obrigado pela atenção, aproveitando que vai fazer testes, achei outro bug, se eu colocar um código de serviço nas configurações e criar um produto com código de serviço igual o geral, ele gera 2 notas, porem, o correto seria ele verificar se o código é o mesmo e gerar apenas uma nota.

**Comment by andrekutianski** [comment]
@ibinetwork fiz uma bateria de testes para tentar reproduzir e identificar o problema mencionado, realizei verificações desde a versão beta (2.0) até a v1.4.4 (a versão anterior a sua atualização) usando as versões do WHMCS desde a 7.10 (obsoleta) até a 8.4.1 (mais recente).

Em todos os cenários de avaliação **as notas fiscais não foram emitidas além da primeira fatura** como aconteceu com você.

Como este resultado foi-me bastante estranho, eu refiz todos os testes em laboratórios com o WHMCS recém-instalado e apenas com o módulo ativo, e novamente a geração da NF não passou da primeira fatura na execução da cron diária.

Todas as outras execuções e automações do módulo ocorreram como o esperado, mas na geração das faturas sempre o mesmo resultado do seu cenário.

Em conclusão, consegui reproduzir o problema, ao que me indica os resultados a questão parece ser anterior a versão 1.4.4, o que não faria sentido já que tudo esta a funcionar corretamente até a atualização para a 1.4.6 como você descreveu.

Estou preparando uma correção para esta questão.

**Comment by ibinetwork** [comment]
> @ibinetwork estou concluindo os últimos testes no WHMCS 8.2 para liberar esta correção. Implementei primeiramente a atualização na versão 2 do módulo devido que esta será a versão ativa, portanto recomendo a preparação para atualização da sua versão para a mais recente assim que concluir a implementação desta correção.
> 
> Temos uma documentação dedicada a ajudar no processo de atualização da v1 para a v2 neste link https://nfe.github.io/whmcs-addon/docs/atualizacao/

Sensacional... aguardando atualização para aplicar por aqui. Muito obrigado!

**Comment by andrekutianski** [comment]
@ibinetwork criei uma nova versão (beta) com as correções para esta questão e também a implantação de novos recursos https://github.com/nfe/whmcs-addon/releases/tag/v2.1.0-beta

**Comment by ibinetwork** [comment]
> @ibinetwork criei uma nova versão (beta) com as correções para esta questão e também a implantação de novos recursos https://github.com/nfe/whmcs-addon/releases/tag/v2.1.0-beta

Atualizei o módulo com essa versão e ao gerar as faturas gerou todas a notas, porem, ele gerou uma nota individual para cada serviço, ou seja, se o cliente tinha 2 ou mais serviços onde era para gerar apenas uma nota com o valor total, ele gerou varias notas fiscais.

Inclusive precisava de uma solução urgente, pois vai causar muito problema com clientes.

Grato.

**Comment by ibinetwork** [comment]
Emitiu varias notas duplicadas :(

**Comment by ibinetwork** [comment]
Outro detalhe, 2 clientes tinha um item negativo pois era desconto na fatura e o módulo esta tentando emitir nota com o valor negativo kkkk

**Comment by andrekutianski** [comment]
@ibinetwork na atualização você seguiu os passos para migração e desativação da versão anterior (v1.4)?

**Comment by ibinetwork** [comment]
> @ibinetwork na atualização você seguiu os passos para migração e desativação da versão anterior (v1.4)?

Sim, passo a passo. tudo certinho.

**Comment by ibinetwork** [comment]
Minha maior preocupação foi o fato de emitir uma nota separada para cada item da fatura.

**Comment by andrekutianski** [comment]
> > @ibinetwork criei uma nova versão (beta) com as correções para esta questão e também a implantação de novos recursos https://github.com/nfe/whmcs-addon/releases/tag/v2.1.0-beta
> 
> Atualizei o módulo com essa versão e ao gerar as faturas gerou todas a notas, porem, ele gerou uma nota individual para cada serviço, ou seja, se o cliente tinha 2 ou mais serviços onde era para gerar apenas uma nota com o valor total, ele gerou varias notas fiscais.
> 
> Inclusive precisava de uma solução urgente, pois vai causar muito problema com clientes.
> 
> Grato.

agora vi que talvez você tenha atualizado para a primeira versão do beta, depois disso lancei outra release aqui no repositório do projeto https://github.com/nfe/whmcs-addon/releases

**Comment by andrekutianski** [comment]
> Outro detalhe, 2 clientes tinha um item negativo pois era desconto na fatura e o módulo esta tentando emitir nota com o valor negativo kkkk

@ibinetwork obrigado pelo feedback, fiz a correção (#115) para não gerar nota para itens da fatura com valores negativos.

Um detalhe importante, o módulo não irá diferenciar itens de fatura que possuam uma linha com abatimento ou desconto de valor. Por exemplo, se o _item 3_ com valor de R$95 tem um desconto/abatimento descriminado em outro item com valor negativo, o módulo emitirá uma nota para o item, pois não existe uma associação ou vinculação entre eles.

![image](https://user-images.githubusercontent.com/5316107/161403024-80365235-3021-426b-9a3a-ff385d4e22dc.png)

**Comment by andrekutianski** [comment]
> Emitiu varias notas duplicadas :(

sobre as notas duplicadas, colocamos um mecanismo para evitar a geração da mesma nota. Para entender melhor o que pode ter ocorrido precisaria analisar os logs do seu WHMCS, se possível me manda por e-mail mais informações do seu WHMCS e um usuário para que eu possar dar uma olhada.

meu email andre[@]eunarede.com

**Comment by ibinetwork** [comment]
> > Outro detalhe, 2 clientes tinha um item negativo pois era desconto na fatura e o módulo esta tentando emitir nota com o valor negativo kkkk
> 
> @ibinetwork obrigado pelo feedback, fiz a correção (#115) para não gerar nota para itens da fatura com valores negativos.
> 
> Um detalhe importante, o módulo não irá diferenciar itens de fatura que possuam uma linha com abatimento ou desconto de valor. Por exemplo, se o _item 3_ com valor de R$95 tem um desconto/abatimento descriminado em outro item com valor negativo, o módulo emitirá uma nota para o item, pois não existe uma associação ou vinculação entre eles.
> 
> ![image](https://user-images.githubusercontent.com/5316107/161403024-80365235-3021-426b-9a3a-ff385d4e22dc.png)

Bom dia, não faz sentido o módulo emitir uma nota fiscal para cada item da fatura, exceto se o código do serviço for diferente, uma fatura onde todos os itens tem o mesmo código de serviço, tem que emitir apenas uma nota fiscal com o valor total da fatura, assim já levando em consideração qualquer desconto que possa ter.

Outra coisa é disponibilizar um link para baixar a nota fiscal, assim podendo ser adicionado no e-mail ou dentro da fatura.

**Comment by andrekutianski** [comment]
Sobre o link para baixar a nota, a v1.4 já possui este recurso (download do PDF e XML) que foi herdado para a 2.1 mas não adaptado ou refatorado. Estarei verificando se será necessária alguma adaptação ou correção para a 2.1 e estarei postando detalhes nesta questão que temos para esse assunto :point_right: #69

**Comment by ibinetwork** [comment]
> @ibinetwork entendi sua argumentação e compreendi seu ponto de vista com relação à emissão de uma NF para todos os serviços que possuam o mesmo código, podemos planejar uma melhoria nesta questão.
> 
> Sobre o desconto, acredito que o ideal seria considerar cada item de fatura que possua valor negativo, como desconto da nota, e descriminar isso nas informações de emissão. A [API](https://nfe.io/docs/desenvolvedores/rest-api/nota-fiscal-de-servico-v1/#/ServiceInvoices/post_v1_companies__company_id__serviceinvoices) da NFE.io já possuí parâmetros (`DiscountUnconditionedAmount` e `DiscountConditionedAmount`) para esta informação.
> 
> Contudo, para conseguir calcular os descontos (ou valores negativos/abatimentos) de uma fatura corretamente teria de ser possível identificar ou realizar a relação item/desconto sendo que:
> 
>     1. itens com código de serviço personalizado que tenham desconto associado, deverá ser emitida nota fiscal separada com o desconto específico para o produto.
> 
>     2. itens com código de serviço padrão deverão ser emitidos em outra nota (de preferência todos os itens na mesma), calculando qualquer outro desconto que possa existir para os itens.
> 
>     3. O desconto total estará separado (assim como os itens) em notas distintas.
> 
>     4. A nota que inclui todos os itens com código de serviço padrão terão seu desconto totalizado e descriminado como um só (até porque só existe um parâmetro para desconto na API).
> 
> 
> Lembrando que o crucial para que essa lógica funcione é conseguir realizar a relação item/desconto, então estou avaliando se é possível ou há alguma forma no lado do WHMCS de conseguir isso.

Entendo que a ideia é atender a todos que usam o módulo, mas ao meu ver não precisa ser nada complexo, e sim apenas pegar o valor total e gerar a nota e pronto.

Como faço para voltar ao módulo 1.4.6 que apesar do bug que iniciou essa conversa, estava me atendendo gerando apenas uma nota por fatura e funcionando o link para o PDF.

**Comment by andrekutianski** [comment]
@ibinetwork implementei novas funcionalidades e várias melhorias na versão [v2.1](https://github.com/nfe/whmcs-addon/releases/tag/v2.1.0) que além de corrigir este problema, também tem nova rota de download do PDF (#69), calculo do desconto (#118) e consolidação das notas (#119).
