### ISSUE TITLE
[SUGESTÃO] emitir nota para itens faturaveis

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#111]
As notas não estão sendo emitida para itens faturáveis do WHMCS.

Por exemplo, o addon da NFE  esta configurado para emitir nota fiscal após confirmação de pagamento. Entretanto especificamente este cliente  esta configurado para que a nota seja emitida assim que a fatura é gerada. Nos itens faturáveis do WHMCS a nota não esta sendo emitida de acordo com a configuração do cliente. Todas as notas dos itens faturáveis estou precisando emitir manualmente dentro da fatura. Segue imagem de onde tem os itens faturáveis do WHMCS no perfil do cliente.

![Screenshot from 2022-03-15 15-53-59](https://user-images.githubusercontent.com/636225/158450851-af96f868-f451-4d8a-ba99-3c263a13e67f.png)

Obrigado.

**Comment by andrekutianski** [comment]
@souzadavi acredita que também existira a necessidade de personalizar o código de serviço para itens faturáveis também, assim como nos produtos/serviços?

**Comment by andrekutianski** [comment]
realizei testes na versão 2.1 (beta) com a criação de itens faturáveis e as notas foram emitidas como esperado!

**Comment by souzadavi** [comment]
> @souzadavi acredita que também existira a necessidade de personalizar o código de serviço para itens faturáveis também, assim como nos produtos/serviços?

Sim poderia ser útil, mas para o meu caso especifico ainda não preciso.



> realizei testes na versão 2.1 (beta) com a criação de itens faturáveis e as notas foram emitidas como esperado!
mas o cliente esta definido diferente da opção global de emissão da nota?

**Comment by andrekutianski** [comment]
> mas o cliente esta definido diferente da opção global de emissão da nota?

Realizei testes com clientes com configuração personalizada e global, assim como itens faturados por tempo e itens avulsos. Tanto na geração manual (selecionando os itens e emitindo a nota) quanto pela cron as notas foram geradas.

Também testei com emissão no pagamento, tudo ocorreu como esperado.

**Comment by andrekutianski** [comment]
a partir da versão [v2.1](https://github.com/nfe/whmcs-addon/releases/tag/v2.1.0) é possível emitir nota para itens faturáveis.
