### ISSUE TITLE
atualizar documentação para v2.1

### ISSUE THREAD

**Issue by andrekutianski** [nfe/whmcs-addon#113]
Realizar a atualização da documentação do módulo para refletir as novas funcionalidades e opções para a versão v2.1

**Comment by andercrist** [comment]
Sabem dizer como colocar na fatura o Download do PDF, a documentação ainda está com o caminho antigo.

**Comment by andrekutianski** [comment]
> Sabem dizer como colocar na fatura o Download do PDF, a documentação ainda está com o caminho antigo.

já estou incluindo uma atualização para a exibição do download de PDF e XML na v2.1, mais informações estou descrevendo nesta questão #69

**Comment by andrekutianski** [comment]
adicionar a documentação instruções para exibição das notas na fatura para o cliente (viewinvoice).

**Comment by andrekutianski** [comment]
Documentação da configuração do módulo atualizada para a v2.1 https://nfe.github.io/whmcs-addon/docs/configuracao/

**Comment by andrekutianski** [comment]
@luizdalciconfeio seria interessante atualizar também a documentação disponível no site da NFE.io para refletir as últimas versões e funcionalidades do módulo https://nfe.io/docs/integracoes/plugins/whmcs/#CHANGELOG

**Comment by luizdalciconfeio** [comment]
boa, vou passar para o marketing @andrekutianski

**Comment by andrekutianski** [comment]
apenas ficou pendente atualização da documentação na página de documentação da NFE.io
