### ISSUE TITLE
[BUG] Itens de fatura com valor negativo gera emissão de nota

### ISSUE THREAD

**Issue by andrekutianski** [nfe/whmcs-addon#115]
**Descreva o erro**
Quando uma fatura possuí um item com valor negativo (desconto na fatura) o módulo gera uma nota para o referido item.  Este problema foi reportado em conversa em #108 

**Como reproduzir**
Etapas para reproduzir o comportamento:
1. Emitir uma nota com item com valor negativo

**Comportamento esperado**
Itens com valores negativos não podem ter nota emitida, por se tratar de valor negativo/desconto.

**Screenshots**
![image](https://user-images.githubusercontent.com/5316107/161399177-7a4dcc97-8be7-4cc8-b117-a486ae7d6c7a.png)

**Ambiente e versões:**
 - Versão do módulo: 2.1
 - Versão do WHMCS: 8.4
 - Versão do PHP: 7.4

_Originally posted by @ibinetwork in https://github.com/nfe/whmcs-addon/issues/108#issuecomment-1086165060_

**Comment by andrekutianski** [comment]
conforme implementação de #118 esta questão foi resolvida.

**Comment by ibinetwork** [comment]
Pra mim não faz sentido emitir uma nota para cada item, e sim emitir uma
nota para cada fatura em seu valor total.

Cabe caso os item terem código de serviço diferente, aí sim emitir a nota
desmembrado.

Em sáb., 2 de abr. de 2022 19:04, Andre Bellafronte Kutianski <
***@***.***> escreveu:
