### ISSUE TITLE
[BUG] Status da Nota Fiscal

### ISSUE THREAD

**Issue by andercrist** [nfe/whmcs-addon#116]
**Descreva o erro**
A Nota fiscal foi emitida mas fica com status "Processando" no whmcs.
![Captura de tela de 2022-04-03 23-02-20](https://user-images.githubusercontent.com/12820524/161462128-1312ced4-4d7e-44d2-b59a-22f2d442f286.png)
![Captura de tela de 2022-04-03 23-02-40](https://user-images.githubusercontent.com/12820524/161462162-2176623b-2bef-42db-a3c6-3f840bf38a39.png)

**Ambiente e versões:**
 - Versão do módulo: release-2.1.0
 - Versão do WHMCS: 8.4.1
 - Versão do PHP: 7.3

**Comment by andercrist** [comment]
Alterei o webhook e assim mesmo deu problemas. Não atualiza o status.

**Comment by andrekutianski** [comment]
> Alterei o webhook e assim mesmo deu problemas. Não atualiza o status.

@andercrist poderia me informar se no seu painel da NFE.io o webhook está presente, e qual o endereço que está enviando as informações? (pode omitir seu domínio)

**Comment by andercrist** [comment]
https://xxx.com.br/modules/addons/NFEioServiceInvoices/callback.php
Nos logs tive o retorno: 40.118.184.97 - - [04/Apr/2022:11:29:46 -0300] "POST /modules/addons/NFEioServiceInvoices/callback.php HTTP/1.1" 200 5 "-" "HookShoot/2.0" "-"

**Comment by andrekutianski** [comment]
O caminho está correto, e pelo log o retorno ocorreu para o módulo.

Você conseguiria localizar o registro diretamente na tabela para observarmos os dados das colunas? As informações das notas ficam em `mod_nfeio_si_serviceinvoices`. Ao receber os dados do webhook o módulo atualiza os dados das notas nesta mesma tabela.

**Comment by andercrist** [comment]
Segue em anexo
![Captura de tela de 2022-04-04 14-41-39](https://user-images.githubusercontent.com/12820524/161600827-2feb0dca-bbd2-421e-8ff5-8bcd4f056047.png)

**Comment by andercrist** [comment]
Alterei para modo teste e parece que agora está funcionando, como foi apenas uma nota fiscal em produção, vou esperar as próximas para confirmar.

**Comment by andrekutianski** [comment]
> Alterei para modo teste e parece que agora está funcionando, como foi apenas uma nota fiscal em produção, vou esperar as próximas para confirmar.

Você está com o registro de eventos (logs) dos módulos, ativado? Quando a API da NFE.io dispara o hook com as informações para atualização do status da nota, um evento é registrado. Seria interessante ver qual o motivo desse gatilho não ter sido processado.

**Comment by andercrist** [comment]
Deixei ativado conforme o print.
![Captura de tela de 2022-04-06 11-52-19](https://user-images.githubusercontent.com/12820524/162003542-9e967909-16fa-469f-949b-54b93f739aab.png)

Realmente em modo produção está com algum problema, no teste funciona normal, apenas em produção.
Segue o log de hoje de madrugada que foi detectado o pagamento de 5 faturas.
![Captura de tela de 2022-04-06 10-42-01](https://user-images.githubusercontent.com/12820524/162003781-d432134b-5695-4a3e-ac2a-b0ed89875d1e.png)

Segue as notas:
![Captura de tela de 2022-04-06 11-58-11](https://user-images.githubusercontent.com/12820524/162005229-37f39743-b966-413e-ae63-20cf0b4632bc.jpg)
![Captura de tela de 2022-04-06 11-55-09](https://user-images.githubusercontent.com/12820524/162005257-6d0129a2-e483-4e35-8150-b4317c5bb150.jpg)

**Comment by andercrist** [comment]
Sem falar que o botão está ativo para emitir a nota, se clicar ele tenta emitir novamente, não entendi se é normal isso.

**Comment by andrekutianski** [comment]
@andercrist enviei uma atualização para a branch [release-2.1.0](https://github.com/nfe/whmcs-addon/tree/release-2.1.0) onde inseri novos registros de logs (388bca4a0324972e6b6848e79fb7acb4c270a8b3) para o callback e também melhorei os existentes para facilitar a busca nos logs do módulo no WHMCS. Peço que atualize seu módulo (você precisará baixar o zip dessa branch ou clonar em sua maquina local) com os arquivos desta branch para vermos melhor todo o fluxo de resposta para o webhook. Acredito que teremos mais informações agora para entender em qual estágio a atualização do status está falhando.

Dica: use o campo de busca nos logs dos módulos para filtrar os resultados referente ao callback, fazendo a busca por `callback` no campo _Action_ (imagem abaixo).

![image](https://user-images.githubusercontent.com/5316107/162086352-3f5f83b4-7811-44c0-8d48-f018bb92cd95.png)

**Comment by andercrist** [comment]
Bom dia! Rapaz você é muito bom! Parabéns! Vou estar atualizando e assim que tiver novidades dos logs adiciono aqui. Muito obrigado!

**Comment by andercrist** [comment]
Meu irmão, já vou pedir desculpas antecipado, descoberto o problema, estava ativo o Ambiente de Desenvolvimento nas configurações.
![Captura de tela de 2022-04-07 10-57-29](https://user-images.githubusercontent.com/12820524/162216537-40af3e62-5890-47b1-a109-b9d34e4e4348.png)
Gerando o erro.
![Captura de tela de 2022-04-07 10-58-03](https://user-images.githubusercontent.com/12820524/162216587-91625c5e-c74d-4086-8de6-499ebaa39b1a.png)

**Comment by andrekutianski** [comment]
Tranquilo @andercrist, que bom que com os novos logs conseguimos identificar! 

Agora desabilite o registro de logs de módulo no WHMCS para não "entupir" seu banco de dados :smile:
