### ISSUE TITLE
[BUG] Botão Emitir NFSe

### ISSUE THREAD

**Issue by andercrist** [nfe/whmcs-addon#117]
**Descreva o erro**
Quando a nota fiscal esta com o status emitida o botão fica desativado mas permanece clicável gerando outra nota fiscal.

![Captura de tela de 2022-04-07 10-55-24](https://user-images.githubusercontent.com/12820524/162217400-d050cb52-ae82-4980-ac6f-1e7d50bfdeab.jpg)

**Ambiente e versões:**
 - Versão do módulo: release-2.1.0
 - Versão do WHMCS: 8.4.1
 - Versão do PHP: 7.3

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by andercrist** [comment]
Testado, solucionado, obrigado!

**Comment by andrekutianski** [comment]
manterei a questão em aberto até lançamento da versão geral v2.1
