### ISSUE TITLE
[SUGESTÃO] abertura de nota fiscal da fatura sem ser via popup

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#120]
Na fatura do WHMCS quando inserido o código para abrir o link de nota fiscal, a mesma é aberta via popup. Os navegadores por padrão bloqueia este tipo de comportamento e isso gera um suporte, pois boa parte dos usuários não conseguem abrir a nota fiscal devido ao bloqueio do navegdor.

É possível que a nota fiscal PDF ou XML seja aberta através de uma nova aba, ou simplesmente fazer o download do arquivo rapidamente sem necessidade de configuração extra no navegador?

Obrigado.

**Comment by andrekutianski** [comment]
@souzadavi obrigado pela sua sugestão. Atualmente, na visualização do cliente, quando o mesmo possuí uma nota viculada a sua fatura, as opções de download do PDF e XML são exibidas em um painel ao final da página da visualização da fatura. Os links exibidos para download são tags padrões HTML _<a>_, que abrem em uma nova janela.

https://github.com/nfe/whmcs-addon/blob/main/modules/addons/NFEioServiceInvoices/lib/templates/clientarea/viewinvoice.tpl#L59

No lado servidor, o PHP gera os respectivos arquivos e "força" o navegador a reconhecer como um download, evitando que seja exibido no navegador (e não baixado).
