### ISSUE TITLE
Configuração Código de Serviço

### ISSUE THREAD

**Issue by jefferson333** [nfe/whmcs-addon#122]
Após concluída a instalação do módulo versão 2.1.0, ao tentar configurar os códigos de serviço individuais aparece o seguinte erro:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mod_nfeio_si_productcode.iss_held' in 'field list' (SQL: select `tblproducts`.`id`, `tblproducts`.`name`, `mod_nfeio_si_productcode`.`code_service`, `mod_nfeio_si_productcode`.`iss_held` from `tblproducts` left join `mod_nfeio_si_productcode` on `tblproducts`.`id` = `mod_nfeio_si_productcode`.`product_id` order by `tblproducts`.`id` desc)

Etapas para reproduzir o erro:
Addons->NFE.io NFSe->Configurações-> Código de Serviço

Vejo que a tabela mod_nfeio_si_productcode está criada, porém não existe a coluna iss_held nela.

**Ambiente e versões:**
 - Versão do módulo: 2.1.0
 - Versão do WHMCS: 8.3.2
 - Versão do PHP: 7.4.26

**Comment by andrekutianski** [comment]
@jefferson333 estou realizando alguns testes aqui para identificar qual o problema na ativação que não gerou esta coluna na tabela. Um paliativo rápido seria criar esta coluna na tabela.

**Comment by andrekutianski** [comment]
> OK, eu posso criar a coluna, mas ainda resta o problema da obrigatoriedade da Inscrição Municipal #123 , que impede que eu salve a configuração.

Neste caso uma maneira de contornar é criar o campo adicional necessário para a inscrição municipal e mantê-lo oculto para apenas poder indicar  o mesmo na configuração do módulo. 

O módulo necessita do campo personalizado, mesmo que você não o esteja utilizando ou nem pretenda utilizar (mantendo ele oculto do cliente).

**Comment by andrekutianski** [comment]
> @andrekutianski qual tipo (string, float, etc..) e tamanho do campo iss_held, para que eu possa criar manualmente?

Já estou disponibilizando uma correção, realmente há um erro na query de seleção quando acessa a página de configuração de códigos de serviços personalizados. Minha sugestão para inserir manualmente a coluna não irá resolver.

**Comment by jefferson333** [comment]
@andrekutianski essa nova versão resolveu esse problema, obrigado!

**Comment by souzadavi** [comment]
consegui resolver o problema de emissão com esta nova versão, mas mesmo assim ainda não estou conseguindo emitir nota fiscal.
