### ISSUE TITLE
Inscrição Municipal

### ISSUE THREAD

**Issue by jefferson333** [nfe/whmcs-addon#123]
Não coleto a Inscrição Municipal dos meus clientes, pois nunca foi necessário.

No módulo v1.4.6 não utilizo o campo Inscrição Municipal e as notas são emitidas sem problemas.

Na versão do módulo 2.1.0 aparece a mensagem "Campo obrigatório Inscrição Municipal está ausente." e não me deixa salvar as configurações sem informar o campo de Inscrição Municipal.

Para que a versão 2.1.0 do módulo funcione corretamente agora é obrigatório ter um campo de Inscrição Municipal para coletar essa informação do cliente?

O ideal é ser opcional e não obrigatório a Inscrição Municipal.

**Comment by andrekutianski** [comment]
Uma maneira de contornar esta situação é criar o campo adicional necessário para a inscrição municipal e mantê-lo oculto para apenas poder indicar o mesmo na configuração do módulo.

O módulo necessita do campo personalizado, mesmo que você não o esteja utilizando ou nem pretenda utilizar (mantendo ele oculta do cliente).
