### ISSUE TITLE
[BUG] Impossibilidade de cancelamento e reemissão de NF

### ISSUE THREAD

**Issue by andrekutianski** [nfe/whmcs-addon#125]
**Descreva o erro**
Ao tentar cancelar uma NF é retornado uma mensagem de erro pelo módulo e também não é mais possível reemitir NF pois não é exibido opção para o mesmo.

**Como reproduzir**

* Tentar cancelar uma NF cujo status difira de emitida (_issued_);
* Tentar realizar uma reemissão de nota;

**Comportamento esperado**

* Conseguir realizar o cancelamento de uma nota cujo status não seja "emitida" (_issued_);
* Poder realizar a reemissão de qualquer nota que tenha sido cancelada;

**Ambiente e versões:**

 - Versão do módulo: v2.1
 - Versão do WHMCS: v8.x
 - Versão do PHP: N/A

**Contexto adicional**

Notas fiscais cujo status sejam “emitida” estão sendo canceladas conforme esperado (mas sem possibilidade de reemissão), na versão 1.4 era possível cancelar uma NF mesmo que não tenha sido emitida corretamente.

**Comment by souzadavi** [comment]
Conseguimos cancelar a nota pela fatura, mas dentro da fatura não tem um botão para reemitir a nota fiscal.

**Comment by andrekutianski** [comment]
> Conseguimos cancelar a nota pela fatura, mas dentro da fatura não tem um botão para reemitir a nota fiscal.

@souzadavi você pode reemitir a nota a partir das ações disponíveis na tabela disponível no módulo

![image](https://user-images.githubusercontent.com/5316107/172184457-91d56336-d024-4491-a72d-6067136cc1cc.png)

**Comment by souzadavi** [comment]
não funciona tbm

**Comment by andrekutianski** [comment]
> não funciona tbm

Qual erro apresentou?

**Comment by souzadavi** [comment]
O botão para reemitir a nota fiscal não esta clicável  e na fatura não tem botão para reemitir a nota fiscal.

**Comment by andrekutianski** [comment]
> O botão para reemitir a nota fiscal não esta clicável e na fatura não tem botão para reemitir a nota fiscal.

O botão para reemitir fica disponível apenas para notas que tenham sido canceladas. No momento o botão de reemissão não está presente nas ações existentes na visualização da fatura, apenas na tabela na página de administração do módulo.

Recomendo ativar o registro de log dos módulos para verificar informações avançadas caso você tente cancelar uma nota e não consiga.

**Comment by souzadavi** [comment]
Cara ta bugado este recurso... Vou deletar direto no banco, tem algum problema?

**Comment by souzadavi** [comment]
@andrekutianski muito obrigado pelo suporte, consegui corrigir o problema com sua ajuda deletando direto no banco as informações das notas travadas, e agora esta tudo rodando certinho.

**Comment by andrekutianski** [comment]
Já está disponível a nova versão do módulo que implementa estas correções https://github.com/nfe/whmcs-addon/releases/tag/v2.1.3
