### ISSUE TITLE
[BUG] código IBGE

### ISSUE THREAD

**Issue by jefferson333** [nfe/whmcs-addon#126]
**Descreva o erro**
Não é possível emitir nota fiscal para um cliente da cidade de São Vicente - SP .

**Como reproduzir**
Basta tentar emitir uma nota fiscal para um endereço que seja de São Vicente - SP.
O módulo WHMCS NFE.io está selecionando o código IBGE errado para a cidade de São Vicente - SP .

**Comportamento esperado**
O módulo deveria selecionar o código IBGE correto e emitir a nota fiscal sem problemas.

**Ambiente e versões:**
 - Versão do módulo: 1.4.6
 - Versão do WHMCS: 8.3.2
 - Versão do PHP: 7.4.28

**Contexto adicional**
Seguem as respostas do suporte da NFE.io:

-----------------------------------------------------------
O motivo da rejeição está no código do IBGE informado.

![nfeio](https://user-images.githubusercontent.com/9992335/171924498-19099978-a9aa-42b2-b7f0-c4f872778289.png)

O código IBGE "2413003" representa a São Vicente do Rio Grande do Norte logo a UF seria RN.
O código IBGE de São Vicente/SP é 3551009.

Cada município é reconhecido por um código chamado de código IBGE, ou seja quando você informa uma cidade no plugin do WHCMS essa informação é convertida neste código.

Neste caso pode estar ocorrendo uma das situações: primeira o plugin não está identificando a cidade de São Vicente sendo de São Paulo e sim do Rio Grande do Norte, ou na hora do preenchimento dos dados do tomador acha duas cidades uma São Vicente/SP e a outra São Vicente/RN.

-----------------------------------------------------------

**Comment by andrekutianski** [comment]
@jefferson333 o processo de como o módulo extrai o código IBGE da cidade é com base no CEP informado que é consultado na  API da NFE.io, retornando o código para preenchimento na emissão da nota.

Estou verificando com o time para validar qual o código associado na plataforma para a cidade de  São Vicente - SP.

**Comment by jefferson333** [comment]
@andrekutianski verifiquei que a API do NFE.io é que retorna o código IBGE errado, veja:

CEP: 11310050

https://open.nfe.io/v1/cities/11310050/postalcode

retorna:

{"city":{"code":"2413003","name":"São Vicente"}}

que é o código errado, o correto seria o código 3551009

Informei isso ao suporte da NFE.io no dia 06/06 e estou ainda aguardando um retorno deles.

**Comment by jefferson333** [comment]
Esse problema foi resolvido pela NFE.io, era um erro no código do IBGE para a cidade de São Vicente-SP.
