### ISSUE TITLE
[SUGESTÃO] emissão de nota fiscal pela fatura na área do cliente

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#128]
Na versão 2.0 não encontrei o recurso de emissão de nota fiscal direto pela fatura na área do cliente.

Seria bom dentro do admin do WHMCS tbm conseguir emitir a nota fiscal, sem o redirecionamento para o painel da NFE.io pois o usuário do WHMCS não tem acesso ao painel da NFE.io.

Obrigado.

![Screenshot from 2022-06-07 10-08-35](https://user-images.githubusercontent.com/636225/172387715-3b56eebe-b099-4e35-ae00-9381061b3e3f.png)

**Comment by andrekutianski** [comment]
A partir da versão 2.0 do módulo a exibição das notas na visualização da fatura pelo cliente necessita de um novo código no arquivo do tema ([viewinvoice.tpl](https://github.com/WHMCS/templates-twenty-one/blob/master/viewinvoice.tpl)):

```smarty
{include file="../../modules/addons/NFEioServiceInvoices/lib/templates/clientarea/viewinvoice.tpl"}
```
Este novo código irá exibir uma tabela com as notas existentes em cada fatura para o cliente.

![](https://user-images.githubusercontent.com/5316107/162670459-e63ba40f-9d38-41dd-9f83-18123e5945fa.png)

Recomendamos a inserção da tabela logo acima da linha [268](https://github.com/WHMCS/templates-twenty-one/blob/master/viewinvoice.tpl#L268) do template, assim a tabela será mostrada acima do botão "voltar para a área do cliente" como no exemplo da imagem a cima.

**Comment by andrekutianski** [comment]
> Seria bom dentro do admin do WHMCS tbm conseguir emitir a nota fiscal, sem o redirecionamento para o painel da NFE.io pois o usuário do WHMCS não tem acesso ao painel da NFE.io.

Toda emissão de nota, seja manualmente feita por qualquer administrador do WHMCS ou automaticamente pelas rotinas da plataforma, não necessitam que o usuário ou administrador acessem o painel da NFE.io ou precisem de um usuário específico para poder interagir com o módulo e API.

O único momento em que é necessário usuário para com acesso ao painel da NFE.io é quando um administrador clica em "visualizar" a NF, pois ele será redirecionado em uma nova janela para o portal.

Agora na visualização do cliente, sempre será necessário que ele (ou o administrador na visão do cliente) acessem a fatura para poder baixar as notas, e isso irá requerer autenticação do seu cliente no WHMCS.

**Comment by souzadavi** [comment]
No arquivo: https://github.com/WHMCS/templates-twenty-one/blob/master/viewinvoice.tpl na linha 34 se possível adicionar um ID na tag, assim é possível personalizar e adicionar um link ancora para descer até a área da nota fiscal.

`<div class="container-fluid invoice-container" id="nfeio">`


O único momento em que é necessário usuário para com acesso ao painel da NFE.io é quando um administrador clica em "visualizar" a NF, pois ele será redirecionado em uma nova janela para o portal.
-- exatamente neste momento, seria ótimo se desse para fazer o download da nota sem a necessidade de fazer login no portal da NFE.io. O administrador do WHMCS poderia ter habilidade de fazer o download da nota fiscal direto pelo admin do WHMCS sem necessidade de precisar fazer login no painel da NFE.io.


Obrigado pela prontidão no retorno.

**Comment by andrekutianski** [comment]
> -- exatamente neste momento, seria ótimo se desse para fazer o download da nota sem a necessidade de fazer login no portal da NFE.io. O administrador do WHMCS poderia ter habilidade de fazer o download da nota fiscal direto pelo admin do WHMCS sem necessidade de precisar fazer login no painel da NFE.io.

@souzadavi pedirei para você abrir uma sugestão aqui sobre esta questão então, já que se trata da visualização/download da nota e não da emissão.

> No arquivo: https://github.com/WHMCS/templates-twenty-one/blob/master/viewinvoice.tpl na linha 34 se possível adicionar um ID na tag, assim é possível personalizar e adicionar um link ancora para descer até a área da nota fiscal.

Também peço que se conseguir, separar esta solicitação em outra issue aqui assim fica mais organizado o processo.

Valeu!
