### ISSUE TITLE
[BUG] reemissão de nota fiscal

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#137]
Ao tentar reemitir uma nota fiscal pela área adm do WHMCS esta aparecendo um erro de SQL, que a coluna tics não existe na tabela: mod_nfeio_si_serviceinvoices

Erro ao reemitir NF: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tics' in 'field list' (SQL: insert into `mod_nfeio_si_serviceinvoices` (`invoice_id`, `user_id`, `nfe_id`, `nfe_external_id`, `status`, `services_amount`, `iss_held`, `nfe_description`, `environment`, `issue_note_conditions`, `flow_status`, `pdf`, `rpsSerialNumber`, `created_at`, `updated_at`, `service_code`, `tics`) values.......

Versão modulo: NFE.io NFSe - 2.1.3
WHMCS: Versão: 8.4.1

**Comment by andrekutianski** [comment]
@souzadavi poderia verificar no seu banco esta tabela para checarmos as colunas? 

Uma medida de contorno rápida seria você criar esta coluna.

**Comment by andrekutianski** [comment]
@souzadavi verifiquei no  módulo a coluna mencionada, e a mesma é criada/existente. 

![image](https://user-images.githubusercontent.com/5316107/192115836-00a5e40b-308d-4e3b-8efd-71faec57a089.png)

Recomendo atualização para a última versão disponível do módulo.

**Comment by souzadavi** [comment]
> @souzadavi verifiquei no módulo a coluna mencionada, e a mesma é criada/existente.
> 
> ![image](https://user-images.githubusercontent.com/5316107/192115836-00a5e40b-308d-4e3b-8efd-71faec57a089.png)
> 
> Recomendo atualização para a última versão disponível do módulo.

Obrigado pelas informações eu criei a coluna na mão e problema foi solucionado.
