### ISSUE TITLE
[SUGESTÃO] emissão de nota fiscal via fatura do admin 

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#141]
Para emitir a nota fiscal de um usuário, o administrado do WHMCS precisa fazer login no perfil (área do cliente) usuário ir até fatura e emitir a nota. Seria possível habilitar a emissão da nota fiscal via admin da fatura do usuário? 

Obs.: atualmente o botão redireciona para o site da NFE.io e o usuário precisa ter os dados de acesso para visualizar.

URL no qual gostaria de emitir a nota fiscal sem necessida de fazer login no site da NFE.io:
.com.br/admin/invoices.php?action=edit&id=29708

![image](https://user-images.githubusercontent.com/636225/195098560-78484476-3549-4c99-8feb-cb00da1fd492.png)

Obrigado.

**Comment by andrekutianski** [comment]
É possível realizar emissão da NF na tela da fatura, pela área do administrador. A NF também pode ser emitida de forma automática ou conforme as configurações definidas no módulo. Temos um manual com instruções e informações sobre a configuração de emissão da NF disponível em https://nfe.github.io/whmcs-addon/docs/configuracao/

**Comment by andrekutianski** [comment]
Também existe a possibilidade de você inserir para o seu cliente as opções de download da NF diretamente quando o mesmo acessar a visualização da sua fatura. Instruções de como inserir o download da NF para seu cliente também estão disponíveis no manual em https://nfe.github.io/whmcs-addon/docs/configuracao/#link-da-nota-na-fatura
