### ISSUE TITLE
Erro ao ativar o módulo

### ISSUE THREAD

**Issue by fernandogobah** [nfe/whmcs-addon#146]
Ocorreu o seguinte ao tentar ativar o módulo.
FPM PHP 8.1
MariaDB 10
WHMCS 8.6.1

Error: Attempt to modify property "connection" on null in /config/www/whmcs/modules/addons/NFEioServiceInvoices/lib/vendor/whmcsexpert/whmcsexpert/src/WHMCSExpert/mtLibs/MySQL/Query.php:69
Stack trace:
#0 /config/www/whmcs/modules/addons/NFEioServiceInvoices/lib/vendor/whmcsexpert/whmcsexpert/src/WHMCSExpert/mtLibs/process/AbstractMainDriver.php(104): WHMCSExpert\mtLibs\MySQL\Query::useCurrentConnection()
#1 /config/www/whmcs/modules/addons/NFEioServiceInvoices/lib/Addon.php(204): WHMCSExpert\mtLibs\process\AbstractMainDriver::I(true)
#2 /config/www/whmcs/modules/addons/NFEioServiceInvoices/NFEioServiceInvoices.php(78): NFEioServiceInvoices\Addon::activate()
#3 /config/www/whmcs/admin/configaddonmods.php(0): NFEioServiceInvoices_activate()
#4 {main}

**Comment by andrekutianski** [comment]
@fernandogobah você realizou a instalação conforme as instruções disponibilizadas em https://nfe.github.io/whmcs-addon/docs/instalacao/ ?

Parece que o módulo não está conseguindo acessar a conexão com seu banco de dados, vou tentar verificar o motivo disso.

**Comment by fernandogobah** [comment]
Boa tarde Andre, sim eu fiz a instalação conforme o passo a passo orientado na documentação da NFe.io (https://nfe.io/docs/integracoes/plugins/whmcs/)
Os demais módulos que utilizo como por exemplo o da PagHiper está operando normalmente.

**Comment by fernandogobah** [comment]
Alguma novidade? Fiz o teste na última versão lançada dia 08/02 e continua com o mesmo erro.

**Comment by andrekutianski** [comment]
@fernandogobah estou tendo alguns problemas para testar nas versões já que o WHMCS suspendeu minhas licenças de desenvolvimento e isso está me atrasando nos testes. Agradeço sua paciência.

**Comment by andrekutianski** [comment]
#149

**Comment by andrekutianski** [comment]
@fernandogobah lançamos uma nova versão que corrige o problema de compatibilidade. Você pode baixar em https://github.com/nfe/whmcs-addon/releases/tag/v2.1.8
