### ISSUE TITLE
Compatibilidade com PHP 8.1

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#149]
O módulo da NFE.io é compatível com o PHP 8.1?

Obrigado.

**Comment by souzadavi** [comment]
Warning: Private methods cannot be final as they are never overridden by other classes in /home/li544ac/whmcs/modules/addons/NFEioServiceInvoices/lib/vendor/whmcsexpert/whmcsexpert/src/WHMCSExpert/mtLibs/process/AbstractMainDriver.php on line 69

![Screenshot from 2023-03-01 14-29-44](https://user-images.githubusercontent.com/636225/222216919-c455126c-8c7b-4d35-af92-610e407f1b62.png)

Precisamos atualizar o PHP para 8.1

**Comment by feperrella** [comment]
Tenho este erro acontecendo, acredito que seja devido a compatibilidade com PHP 8.1, se isto ajudar a identificar o problema:

PHP 8.1.16
ionCube Loader 12.0.5
WHMCS 8.6.1

`Error: Attempt to modify property "connection" on null in /modules/addons/NFEioServiceInvoices/lib/vendor/whmcsexpert/whmcsexpert/src/WHMCSExpert/mtLibs/MySQL/Query.php:69
Stack trace:
#0 /modules/addons/NFEioServiceInvoices/lib/vendor/whmcsexpert/whmcsexpert/src/WHMCSExpert/mtLibs/process/AbstractMainDriver.php(104): WHMCSExpert\mtLibs\MySQL\Query::useCurrentConnection()
#1 /modules/addons/NFEioServiceInvoices/NFEioServiceInvoices.php(133): WHMCSExpert\mtLibs\process\AbstractMainDriver::I()
#2 /addonmodules.php(0): NFEioServiceInvoices_output(Array)
#3 {main}`

**Comment by andrekutianski** [comment]
> Tenho este erro acontecendo, acredito que seja devido a compatibilidade com PHP 8.1, se isto ajudar a identificar o problema:
> 
> PHP 8.1.16 ionCube Loader 12.0.5 WHMCS 8.6.1
> 
> `Error: Attempt to modify property "connection" on null in /modules/addons/NFEioServiceInvoices/lib/vendor/whmcsexpert/whmcsexpert/src/WHMCSExpert/mtLibs/MySQL/Query.php:69 Stack trace: #0 /modules/addons/NFEioServiceInvoices/lib/vendor/whmcsexpert/whmcsexpert/src/WHMCSExpert/mtLibs/process/AbstractMainDriver.php(104): WHMCSExpert\mtLibs\MySQL\Query::useCurrentConnection() #1 /modules/addons/NFEioServiceInvoices/NFEioServiceInvoices.php(133): WHMCSExpert\mtLibs\process\AbstractMainDriver::I() #2 /addonmodules.php(0): NFEioServiceInvoices_output(Array) #3 {main}`

Correto @feperrella o erro é devido a necessidade de compatibilidade com PHP 8.x.  O erro na ativação mencionado em #146 também tem relação com compatibilidade.

Já estamos trabalhando na refatoração.

**Comment by andrekutianski** [comment]
Uma nova versão foi disponibilizada que implementa compatibilidade com PHP 8 e WHMCS 8.6 https://github.com/nfe/whmcs-addon/releases/tag/v2.1.8
