### ISSUE TITLE
Erro ao fazer o encoding de caracteres especiais na razão social do tomador do serviço

### ISSUE THREAD

**Issue by caiorasc** [nfe/whmcs-addon#16]
Pegamos um caso em que a razão social do tomador do serviço tinha um "E" comercial (&), a nota fiscal foi enviada para API da NFE.io com o seguinte texto no lugar do caractere especial: &amp ;

**Comment by souzadavi** [comment]
Olá @caiorasc veja se entendi certo, por exemplo: a Razão Social é: Tomador & Serviços, mas a NFE Recebeu apenas o caractere: &. Seria isso?

**Comment by caiorasc** [comment]
Oi @souzadavi não. 
Sendo a razão social: Tomador & Serviços. A API da NFE Recebeu assim: Tomador &amp Serviços.
Eu escrevi errado ali na issue, desculpa

**Comment by souzadavi** [comment]
@caiorasc obrigado pela informação. Fiz alguns testes por aqui e não consegui solucionar. Por favor verifique se o lado de vcs esta validando esse tipo de situação e me deixe saber.

**Comment by souzadavi** [comment]
Ajustado na versão: v1.2.7
