### ISSUE TITLE
plugin está emitindo notas de cobranças antigas (desde 2013)

### ISSUE THREAD

**Issue by kitajoao** [nfe/whmcs-addon#18]
Avaliar como o plugin está gerando as notas das cobranças criadas. Ao que consta, cobranças antigas que não deveriam possuir notas a serem emitidas estão com a emissão ocorrendo.

Em outras palavras,a integração deveria emitir notas somente nas faturas que seriam geradas a partir do momento da ativação da integração. Porém o plugin está buscando a informação de cobranças antigas (desde 2013) e está gerando uma nota indevida.

**Comment by souzadavi** [comment]
Olá @kitajoao não consegui reproduzir esse erro, poderia verificar se o WHMCS do usuário esta com a data formatada em DD/MM/YYYY ?

ADMIN WHMCS >> Configurações gerais >> Formato da Data

**Comment by kitajoao** [comment]
vou conversar com o cliente e te retorno.

**Comment by gblmarquez** [comment]
@souzadavi conforme conversamos com o Fabio precisamos das seguintes funcionalidades
- Incluir opção de emissão manual de notas fiscais
- Incluir opção da data de início para emissão quando for o modo automático

**Comment by souzadavi** [comment]
@gblmarquez opção de emissão manual de nota fiscal inserido.

**Comment by gblmarquez** [comment]
@souzadavi perfeito! já avisamos o cliente.

agora precisamos implementar a funcionalidade de a partir de qual data de criação ou data de pagamento das faturas devem ser emitidas as notas fiscais.

**Comment by souzadavi** [comment]
Funcionalidade aplicada na versão: v1.2.7
