### ISSUE TITLE
Possibilidade de inserção de mais de um código de serviço na emissão da nota no plugin

### ISSUE THREAD

**Issue by kitajoao** [nfe/whmcs-addon#19]
Bom dia.

Surgiu a demanda de ser possível informar mais de um código de serviço para a emissão da nota.

Um cliente possui dois códigos de serviço e por conta da configuração do plugin faz emissão somente com um dos dois. 

Contudo, ele precisa realizar a emissão com mais de um código.

**Comment by souzadavi** [comment]
@kitajoao essa demanda é possível. Por favor agende uma reunião para a gente levantar os requisitos e definir essa demanda. Obrigado.

**Comment by souzadavi** [comment]
Recurso aplicado na versão: v1.2.7
