### ISSUE TITLE
Opção de agendamento de emissão de fatura não funciona

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#2]
Olá boa noite, a opção de agendar emissão de faturas após X dias do pagamento da fatura não esta funcionando.

-> Agendar Emissão: Número de dias após o pagamento da fatura que as notas devem ser emitidas. Preencher essa opção desativa a opção anterior;

![Captura de tela de 2020-07-21 22-57-24](https://user-images.githubusercontent.com/636225/88125379-9058c300-cba5-11ea-94ee-621c171e493e.png)

Obrigado.

**Comment by mauriciogofas** [comment]
@ souzadavi,
para um diagnóstico mais eficiente, precisamos ver o log completo gerado ao rodar o cron diário do WHMCS, que mostra todas as informações processadas para envio à API e as respectivas respostas do processamento dos dados.
Caso o debug esteja inativo, siga os passos a seguir para obter o log de depuração:

1) Acesse no painel administrativo do WHMCS, Opções > Módulos Addon > Gofas NFE.io > Configurar
2) Ative a opção "Debug" nas configurações do Addons;
3) Ative o debug de módulo clicando em "Ativar Log de Debug" na seguinte página do painel do WHMCS: Utilitários > Logs > Log de Módulo;

Você pode esperar o próximo cron diário rodar, ou forçar o cron acessando www.urldowhmcs.com/crons/cron.php?command=all&options=force. Após coletar os dados, nos envie por este formulário os logs, por favor:
https://gofas.net/contato/?suporte=Ajuda%20/%20Suporte

**Comment by souzadavi** [comment]
Enviado ticket: #2399
obrigado.

**Comment by souzadavi** [comment]
Mauricio boa tarde, algum posicionamento? Conseguiu identificar? Estou precisando muito usar esse modulo. Obrigado.

**Comment by mauriciogofas** [comment]
@souzadavi, a [versão 1.1.3](https://github.com/nfe/whmcs-addon/archive/v1.1.3.zip) resolve erros relacionados ao número do RPS, por favor, teste e nos deixe saber o resultado.

**Comment by souzadavi** [comment]
@mauriciogofas olá boa tarde. Ontem a noite eu atualizei o sistema. Estou usando a versão: v1.2.0 , entretanto hoje as 9 horas, horário do cron. As notas não foram geradas automaticamente. No modulo de log não tem nenhuma mensagem que apresente algum erro e no painel da NFE não tem nenhum tentativa de emissão de nota.

Obrigado.

**Comment by mauriciogofas** [comment]
Preciso ver os logs gerados pelo módulo durante e após a execução do cron diário, separados em requisição e resposta. As notas fiscais geradas manualmente apresentam algum erro?

**Comment by souzadavi** [comment]
Olá @mauriciogofas bom dia, fiz a atualização para o modulo 1.2.1 agora cedo após rodar o cron, portanto a serie do rps ainda esta na versão antiga.

O estranho é que na plataforma do app.nfe.io deveria ter as notas emitidas, entretanto lá aparece apenas as notas que emiti manualmente direto pela fatura no WHMCS.

Esses são os logs da última cron para action: gofas_nfeio


**invoicecreation**

REQUEST
Array
(
    [vars] => Array
        (
            [source] => autogen
            [user] => system
            [invoiceid] => 15962
            [status] => Unpaid
        )

    [gnfe_ibge] => 
    [postifields] => 
)


RESPONSE

Array
(
    [params] => Array
        (
            [access] => 5,1,6
            [version] => 1.2.0
            [intro] => 
            [api_key] => pvzwBy2Ak40b1ds444ffLh6WrwewwcOi9ScvHfZpZShN0uoUgFi
            [company_id] => 5ee8wwq4444980b9c8
            [service_code] => 10802
            [issue_note] => Quando a Fatura é Gerada
            [issue_note_after] => 2
            [cancel_invoice_cancel_nfe] => on
            [debug] => on
            [footer] => 
            [rps_serial_number] => IO
            [rps_number] => 8
        )

    [invoice] => 
    [client] => 
    [queue] => 
    [nfe_for_invoice] => 
    [company] => 
)


**invoicepaid**

REQUEST
Array
(
    [vars] => Array
        (
            [invoiceid] => 15963
        )

    [gnfe_ibge] => 
)


RESPONSE
Array
(
    [params] => Array
        (
            [access] => 5,1,6
            [version] => 1.2.0
            [intro] => 
            [api_key] => pvzwBy2Ak40b1McOi9ScvHfZpdgrcRZGw4ZShN0uxNqVoUgFi
            [company_id] => 5ee800cdb8
            [service_code] => 10802
            [issue_note] => Quando a Fatura é Gerada
            [issue_note_after] => 2
            [cancel_invoice_cancel_nfe] => on
            [debug] => on
            [footer] => 
            [rps_serial_number] => IO
            [rps_number] => 8
        )

    [invoice] => 
    [client] => 
    [queue] => 
    [nfe_for_invoice] => 
)


Obrigado!

**Comment by souzadavi** [comment]
As notas ainda não são emitidas automaticamente após X dias.

**Comment by mauriciogofas** [comment]
No log mostra que apenas a fatura ID 15963 era elegível para emitir NFE, provavelmente você já gerou uma nota fiscal manualmente para essa fatura, por isso o módulo não emitiu a nota.
