### ISSUE TITLE
Integração WHMCS novo cliente plugin

### ISSUE THREAD

**Issue by kitajoao** [nfe/whmcs-addon#20]
Bom dia.

Ontem, em uma nova integração, um cliente se deparou com o seguinte problema.

![image](https://user-images.githubusercontent.com/51325916/98384025-033e5a80-202c-11eb-8d09-25ea93b9f4ff.png)

Não soubemos informar o motivo do problema.

**Comment by souzadavi** [comment]
Esse problema é porque a instalação do módulo não foi concluída com sucesso. Isso pode ocorrer porque o usuário do banco de dados não tem permissão para criar uma nova tabela no banco. Solicite para ele rodar manualmente o SQL dentro do banco do WHMCS dele e deve resolver o problema.

`CREATE TABLE `gofasnfeio` (
  `id` int(10) UNSIGNED NOT NULL,
  `invoice_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `nfe_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `services_amount` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `environment` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `flow_status` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `pdf` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `updated_at` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `rpsSerialNumber` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `rpsNumber` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;`

**Comment by kitajoao** [comment]
Obrigado Davi. Vou orientar o cliente.
