### ISSUE TITLE
Configuração do módulo na Serie RPS altera sozinha

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#3]
Olá boa tarde, a serie do RPS esta alterando sozinha após a emissão de algumas notas.

Ela volta para o valor padrão IO.

![Screenshot from 2020-08-27 12-37-32](https://user-images.githubusercontent.com/636225/91463807-34e3ba00-e862-11ea-9d36-1ddf872a7c25.png)

**Comment by mauriciogofas** [comment]
A série do RPS deve ser alterada automaticamente em alguns casos. Teste a versão 1.2.1, deve resolver a sua dificuldade.

**Comment by souzadavi** [comment]
Olá @mauriciogofas fiz a atualização e notei que a seria de RPS alterou novamente sozinha, agora para 0 antes alterava para IO.

**Comment by mauriciogofas** [comment]
@ souzadavi, teste novamente com a versão 1.2.2, por favor.

**Comment by souzadavi** [comment]
Resolvido, obrigado.
