### ISSUE TITLE
Bloquear emissão de nota fiscal duplicada

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#30]
Ao emitir uma nota fiscal manualmente e o sistema estiver configurado para emitir nota fiscal após confirmação de pagamento. O sistema gera outra nota fiscal.

O sistema precisa verificar se existe nota fiscal emitida para a fatura, se já tiver uma nota fiscal emitida o sistema não deve emitir uma nova nota. Exceto se a nota estiver cancelada.

**Comment by JoaoVictorLNacional** [comment]
previsão de +/- 2h para achar e corrigir o bug

**Comment by souzadavi** [comment]
pull request #32
