### ISSUE TITLE
Habilitar botão para cancelar nota fiscal 

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#33]
Habilitar botão de cancelar nota fiscal quando a nota fiscal estiver como waiting no banco de dados.

**Comment by souzadavi** [comment]
Quando o status da nota estiver em waiting tem que verificar se a nota já foi enviada para a NFE. Se já foi enviada para a NFE a opção de cancelar nota tem que ficar desativada aguardando o retorno da NFE.

As notas não podem ser deletadas do banco, deve manter todas as tentativas de emissão de nota fiscal.

Em alguns casos pode dar erro na emissão da nota fiscal entre nfe e prefeitura o status da nota fica como: issuefailed esse status deve atualizar a nota fiscal dentro do WHMCS.

Na fatura mostrar todas as tentativas de emissão de nota bem sucedidas ou não.

**Comment by souzadavi** [comment]
Ajustado versão 1.3.0 no pull request: https://github.com/nfe/whmcs-addon/pull/40

**Comment by souzadavi** [comment]
Faltou o Item: 

Na fatura mostrar todas as tentativas de emissão de nota bem sucedidas ou não.

**Comment by souzadavi** [comment]
Verificar opção de cancelar nota fiscal e emitir novamente.

**Comment by andrekutianski** [comment]
esta funcionalidade está implementada e operacional na versão 2, devido a isso estou fechando esta issue.
