### ISSUE TITLE
Endereço de e-mail não esta sendo enviado para a NFE

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#36]
O módulo de nota fiscal não esta enviando o endereço de e-mail para NFE.io.

**Comment by JoaoVictorLNacional** [comment]
https://github.com/LinkNacional/whmcs-addon/commit/0a74aac93290c81afcd46896a56879a13df9ee42

**Comment by JoaoVictorLNacional** [comment]
https://github.com/LinkNacional/whmcs-addon/pull/18

**Comment by souzadavi** [comment]
Pull request com correção: 1.2.10 correção bug enviar endereço de e-mail na nota.
