### ISSUE TITLE
Emissão de nota fiscal duplicada para mesma fatura

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#4]
Olá @mauriciogofas boa tarde. No dia 30 o sistema rodou a emissão de nota fiscal automaticamente, entretanto o sistema emitiu em duplicidade a nota fiscal para uma fatura que já tinha nota fiscal emitida.

O problema: alguns clientes precisam da nota antes de fazer o pagamento, nesse caso eu estou emitindo a fatura manualmente pela fatura do WHMCS e enviando para o cliente.

Após a confirmação de pagamento da fatura, na qual já tinha uma nota emitida antes do pagamento, houve uma nova emissão de nota fiscal. Ou seja, aparentemente o sistema não leva em consideração se já existe uma nota fiscal aberta para a fatura.

**Comment by mauriciogofas** [comment]
Testamos de diversas formas e esse erro não acontece, a menos que a NFE associada à fatura tenha sido cancelada ou a emissão anterior falhou, o módulo não gera uma nova nota fiscal para faturas que já emitiram uma nota.

**Comment by souzadavi** [comment]
Fatura verifica se existe uma nota sendo processada. Evitando a emissão em duplicidade da nota fiscal para a mesma fatura.
