### ISSUE TITLE
Requests inválidos

### ISSUE THREAD

**Issue by gblmarquez** [nfe/whmcs-addon#46]
@souzadavi estamos recebendo requests com esse formato "/v1/companies//serviceinvoices/xxxxxxxxxx".

Acreditamos que seja algo relacionado ao plugin, pois está vindo de uma integração whmcs.

**Comment by souzadavi** [comment]
@gblmarquez esta requisição não esta vindo deste módulo. Se o problema persistir por favor me avise por aqui. Obrigado.
