### ISSUE TITLE
Campos personalizados bloqueiam  a emissão personalizada.

### ISSUE THREAD

**Issue by joaokita** [nfe/whmcs-addon#48]
Se forem configurados campos personalizados além dos que são padrão para a emissão de nota fiscal ("Inscrição Municipal", "CPF" e "CNPJ") não é possível configurar a opção personalizada de emissão de nota, como definido em: https://github.com/nfe/whmcs-addon#emissão-personalizada-de-notas-para-cliente

**Comment by joaokita** [comment]
Se forem configurados campos personalizados além dos que são padrão para a emissão de nota fiscal ("Inscrição Municipal", "CPF" e "CNPJ")  não é possível configurar a opção personalizada de emissão de nota, como definido em: https://github.com/nfe/whmcs-addon#emissão-personalizada-de-notas-para-cliente

**Comment by souzadavi** [comment]
Ajustado na versão 1.4.0. Será necessário reconfigurar todos os usuários do WHMCS. Pois o método antigo estava através de campos personalizados no qual era definido pelo próprio usuário do sistema. Ocasionando possíveis erros de digitação. Agora o sistema trata esta nova opção sem a necessidade do usuário criar os campos personalizados dentro do WHMCS
