### ISSUE TITLE
Erro de emissão de nota fiscal quando o CEP não é encontrado

### ISSUE THREAD

**Issue by souzadavi** [nfe/whmcs-addon#51]
Habilitar o recurso pro usuário admin do WHMCS conseguir cancelar a emissão da nota e solicitar uma nova emissão de nota fiscal direto pela fatura.

![Screenshot from 2021-06-30 17-08-01](https://user-images.githubusercontent.com/636225/124025251-987ccd80-d9c6-11eb-90a4-6e28fcb0afeb.png)

**Comment by brunoferreira-linknacional** [comment]
Anotação: pode ser solucionado editando o arquivo output.php e admininvoicescontrolsoutput.php.

**Comment by andrekutianski** [comment]
recurso já está disponibilizado em versões recentes (v2) do módulo.
