### ISSUE TITLE
Remoção do nome "gofas" do módulo

### ISSUE THREAD

**Issue by luizdalciconfeio** [nfe/whmcs-addon#54]
O Antigo fornecedor que criou o módulo acabou colocando o nome da empresa em diversos lugares.

Precisamos tirar esse nome e padronizar tudo como NFE.io.

Isso inclui renomear:

- Telas
- Views
- Paths
- Arquivos
- Métodos e variáveis
- Nome de classes
- Tabelas de banco de dados

**Comment by souzadavi** [comment]
Ticket duplicado, utilizar o aberto mais antigo: https://github.com/nfe/whmcs-addon/issues/9
