### ISSUE TITLE
Disponibilidade da versão 1.4.0

### ISSUE THREAD

**Issue by abnerjacobsen** [nfe/whmcs-addon#60]
Minha empresa é cliente da NFE.io e no momento usamos uma solução desenvolvida internamente, mas, pretendemos mudar para este addon. Qual a previsão para a liberação da versão 1.4.0 ?

Obrigado.

**Comment by gblmarquez** [comment]
@abnerjacobsen PR liberado. @souzadavi você precisa de algum procedimento adicional para liberar a versão?

**Comment by souzadavi** [comment]
Olá @abnerjacobsen obrigado pelo contato, a versão foi liberada.
