### ISSUE TITLE
Desabilitar emissão para determinado cliente

### ISSUE THREAD

**Issue by julianohammerle** [nfe/whmcs-addon#65]
Minha sugestão seria para incluir no novo campo do cadastro do cliente "Emitir nota fiscal quando" uma opção para desabilitar a geração de notas para aquele cliente em específico.

**Comment by souzadavi** [comment]
@julianohammerle esta opção já existe. Qual a versão do módulo que vc esta usando?

**Comment by julianohammerle** [comment]
Olá, estou usando a 1.4.0

**Comment by souzadavi** [comment]
Esta versão já tem o recurso disponível. Por favor veja a descrição na imagem abaixo.

![Screenshot from 2021-08-19 20-08-10](https://user-images.githubusercontent.com/636225/130155501-a938f221-282b-4b3e-814e-24caf47c21ff.png)

**Comment by julianohammerle** [comment]
Mas a minha sugestão é de acrescentar nesse select a opção de "Não gerar nota para este cliente em questão"
