### ISSUE TITLE
Melhorar rota de download de PDF

### ISSUE THREAD

**Issue by luizdalciconfeio** [nfe/whmcs-addon#69]
Atualmente a rota de download do PDF da nota fiscal recebe o invoice_id na rota (formato numérico).

Precisamos alterar essa lógica para receber um hash que seja criptografado com uma chave única da instalação do módulo.

**Comment by andrekutianski** [comment]
Exemplo da nova rota, listagem e download da nota em PDF e XML.

![image](https://user-images.githubusercontent.com/5316107/161873018-2e26c791-dd43-4a70-91c4-2e771dff15bb.png)
