### ISSUE TITLE
Mensagem ao trocar a versão

### ISSUE THREAD

**Issue by julianohammerle** [nfe/whmcs-addon#79]
Quando eu fiz o update da versão 1.4.0 para 1.4.2, apresentou a mensagem abaixo nas configurações e isso me causou dúvidas a respeito se o que fiz está certo ou não e/ou está seguro em manter a versão 1.4.2.
------------
Módulo Nota Fiscal NFE.io para WHMCS v1.4.0
Você está executando a versão mais recente do módulo.
Você está tentando instalar a versão 1.4.2 e a versão anteriormente instalada foi a 1.4.0
 Entretanto, só é permitida a atualização do módulo para frente e de uma em uma versão. Ex.: 1.3.0 para 1.4.0, 1.4.3 para 1.5.0

**Comment by souzadavi** [comment]
É um bug, não impede o funcionamento das notas, logo terá uma atualização para corrigir, obrigado por notificar.
