### ISSUE TITLE
Logo do autor com caminho quebrado

### ISSUE THREAD

**Issue by andrekutianski** [nfe/whmcs-addon#81]
a Logo do autor não está sendo exibida na página de instalação do módulo.

![Screenshot from 2021-09-09 00-26-30](https://user-images.githubusercontent.com/5316107/132617537-57120d20-86d5-4eaf-8e1f-004624c44f8b.png)

Está faltando no caminho da imagem "/" na separação entre o domínio e o diretório "admin"

![image](https://user-images.githubusercontent.com/5316107/132617672-8ffca20c-239b-4c22-bbb9-2ba5cfd7eee1.png)

**Comment by andrekutianski** [comment]
O mesmo problema está sendo apresentado no acesso as páginas do módulo quando acessado em _Addon > NFE.io_. Ambos os botões da página redirecionam para os links onde falta uma "/" na separação entre o diretório da administração e a caminho da página, tornando a URL inacessível e retornando um erro de redirecionamento conforme imagem abaixo.

![image](https://user-images.githubusercontent.com/5316107/132750923-ad4ab906-98d2-48df-b275-f74283ac3634.png)

Entre a extensão do domínio e o diretório há ausência da "/" de separação:

* Como está: https://dominio.netadmin/addonmodules.php?module=gofasnfeio&action=code_product
* Como deveria ser: https://dominio.net/admin/addonmodules.php?module=gofasnfeio&action=code_product

Testado na versão 1.4.3 do módulo no WHMCS 8.2 e 7.10

**Comment by andrekutianski** [comment]
pelo que pude constatar a causa deste problema na URL é originada pelo registro incorreto do parametro _gnfewhmcsadminurl_ realizado na tabela _tblconfiguration_ como pode ser visto na imagem abaixo.

![image](https://user-images.githubusercontent.com/5316107/132769146-d56afea1-dcf7-45f2-80d0-af3050460b2f.png)

Os arquivos [outputsystemlegacy.php](https://github.com/nfe/whmcs-addon/blob/master/modules/addons/gofasnfeio/addonPage/outputsystemlegacy.php#L7) e [outputproduct.php](https://github.com/nfe/whmcs-addon/blob/master/modules/addons/gofasnfeio/addonPage/outputproduct.php#L36) buscam este valor para construir a URL dos links e botões.

**Comment by souzadavi** [comment]
Dentro das configurações do seu WHMCS em configurações gerais, coloque a / nas configurações: 
- Domínio 
- URL do Sistema WHMCS

![Screenshot from 2021-09-09 19-16-36](https://user-images.githubusercontent.com/636225/132769856-ab32accf-9c39-4afb-ba3a-82438614d037.png)

**Comment by andrekutianski** [comment]
Olá, peço que reabra a questão para que eu possa realizar o pull da branch com a correção desta questão no módulo. Obrigado.

**Comment by andrekutianski** [comment]
> Dentro das configurações do seu WHMCS em configurações gerais, coloque a / nas configurações:
> 
> * Domínio
> * URL do Sistema WHMCS
> 
> ![Screenshot from 2021-09-09 19-16-36](https://user-images.githubusercontent.com/636225/132769856-ab32accf-9c39-4afb-ba3a-82438614d037.png)

Entendi sua solução, mas infelizmente isso sempre dependerá do "WHMCS bem configurado", o que torna subjetivo e passível de problema/erro como apresentado aqui. Estou fazendo o PR com uma atualização no módulo que independerá desta configuração que você mencionou quanto de qualquer select realizado [aqui](https://github.com/nfe/whmcs-addon/blob/master/modules/addons/gofasnfeio/addonPage/outputsystemlegacy.php#L7) e [aqui](https://github.com/nfe/whmcs-addon/blob/master/modules/addons/gofasnfeio/addonPage/outputproduct.php#L36)

**Comment by andrekutianski** [comment]
[ATUALIZAÇÃO]

Este problema está ocorrendo em todos os links e botões, inclusive nos botões de ação de emissão da NF dentro da fatura.  Realizei teste com a versão 1.4.3 e 1.3.0 e ambas apresentaram o mesmo problema no WHMCS v8.2

Verifiquei que o paramêtro "URL do Sistema WHMCS" já continha a "/" no final

**Comment by andrekutianski** [comment]
@luizdalciconfeio se possível posso marcar esta questão como resolvida?
