### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by gblmarquez** [nfe/whmcs-addon#9]
@souzadavi precisamos fazer um rebranding do modulo.

**Comment by souzadavi** [comment]
Alterações:
- nome do módulo
- descrição do módulo
- logo do módulo
- alterar pasta (validar se pasta antiga não existe)

**Comment by andrekutianski** [comment]
Definido junto com @luizdalciconfeio o novo nome do módulo Addon para: **nfeio_serviceinvoices**

**Comment by andrekutianski** [comment]
#### Checklist de migração

Checklist com os itens primordiais a serem implementados e verificados para permitir uma migração segura e sem atritos entre a versão anterior a 2.0 (antiga estrutura).

* [ ] webhooks: webhooks atuais devem apontar para novo endereço
* [x] migrar configurações: migrar as configurações atuais do antigo módulo para o novo e evitar configuração
* [x] migrar notas: migrar os dados atuais das notas da tabela _gofasnfeio_ para _mod_nfeio_si_serviceinvoices_
* [x] migrar produtos: migrar os registros dos códigos de serviços personalizado dos produtos da tabela _tblproductcode_ para _mod_nfeio_si_productcode_
* [x] migrar clientes: migrar os registros de emissão de nf personalizados dos clientes da tabela _mod_nfeio_custom_configs_ para _mod_nfeio_si_custom_configs_
* [x] campos obrigatórios: verificar se os campos obrigatórios estão preenchidos e alertar
* [x] estrutura de tabelas: obedecer a estrutura atual das tabelas para menor atrito na migração

**Comment by andrekutianski** [comment]
@luizdalciconfeio o módulo na nova estrutura já está pronto para testes, verificação e validação, na branch refact_9

Para dar como completa as rotinas de migração (fora as já criadas e listadas [aqui](https://github.com/nfe/whmcs-addon/issues/9#issuecomment-945340479)) ainda preciso criar:

* [ ] rotina para criar um  novo webhook com o novo caminho  do callback
* [ ] rotina para desativar o webhook do callback da versão anterior (para evitar problemas com módulos que não foram devidamente migrados)
* [ ] alerta visual no admin caso a versão antiga ainda esteja ativa em paralelo com a nova

Fora as questão mencionadas a cima, já testei todas as rotinas existentes e por aqui o módulo não apresenta nenhum problema, tendo todas as rotinas em operação.

**Comment by andrekutianski** [comment]
> @luizdalciconfeio existira alguma objeção em ter a criação do webhook da nova estrutura automaticamente na instalação/migração?
> 
> Hoje existe uma função que cria webhook, só não consegui encontrar (na antiga estrutura) referência para sua execução. Posso aproveitar ela e garantir que existirá o callback no lado da NFE.io

Aproveitei a lógica atual dos webhooks, efetuando algumas correções e adaptações para a nova estrutura.

**Comment by andrekutianski** [comment]
Iniciando documentação da nova estrutura.

* [ ] Documentação de migração/atualização
* [ ] Documentação de instalação
* [ ] Documentação de configuração

**Comment by andrekutianski** [comment]
Documentação de atualização/migração concluída e disponível em https://nfe.github.io/whmcs-addon/docs/atualizacao

**Comment by andrekutianski** [comment]
Documentação de instalação concluída e disponível em https://nfe.github.io/whmcs-addon/docs/instalacao/

**Comment by andrekutianski** [comment]
Documentação de configuração concluída e disponível em https://nfe.github.io/whmcs-addon/docs/configuracao/

**Comment by andrekutianski** [comment]
branch para a release 2.0.0 pronta emhttps://github.com/nfe/whmcs-addon/tree/release-2.0.0
